# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_ups.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x61mazon_ups.proto\"\x1d\n\nU2AConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\"/\n\x0cU2AConnected\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x0e\n\x06result\x18\x02 \x02(\t\"\xa3\x01\n\rPickupRequest\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x0f\n\x07orderid\x18\x02 \x02(\x03\x12\x13\n\x0bproductName\x18\x03 \x02(\t\x12\x0c\n\x04whid\x18\x04 \x02(\x03\x12\x0c\n\x04wh_x\x18\x05 \x02(\x03\x12\x0c\n\x04wh_y\x18\x06 \x02(\x03\x12\x0e\n\x06\x64\x65st_x\x18\x07 \x02(\x03\x12\x0e\n\x06\x64\x65st_y\x18\x08 \x02(\x03\x12\x12\n\nupsAccount\x18\t \x01(\t\"T\n\x0ePickupResponse\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x10\n\x08tracknum\x18\x02 \x02(\x03\x12\x0f\n\x07orderid\x18\x03 \x02(\x03\x12\x0f\n\x07truckid\x18\x04 \x02(\x03\"3\n\x0f\x44\x65liveryRequest\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x10\n\x08tracknum\x18\x02 \x02(\x03\"4\n\x10\x44\x65liveryResponse\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x10\n\x08tracknum\x18\x02 \x02(\x03\"L\n\nUpdateDest\x12\x0e\n\x06seqnum\x18\x01 \x02(\x03\x12\x10\n\x08tracknum\x18\x02 \x02(\x03\x12\r\n\x05new_x\x18\x03 \x02(\x03\x12\r\n\x05new_y\x18\x04 \x02(\x03\"A\n\x0c\x45rrorMessage\x12\x0b\n\x03\x65rr\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"]\n\nA2URequest\x12\x1e\n\x06pickup\x18\x01 \x03(\x0b\x32\x0e.PickupRequest\x12\"\n\x08\x64\x65livery\x18\x02 \x03(\x0b\x32\x10.DeliveryRequest\x12\x0b\n\x03\x61\x63k\x18\x03 \x03(\x03\"~\n\x0bU2AResponse\x12\x1f\n\x06pickup\x18\x01 \x03(\x0b\x32\x0f.PickupResponse\x12#\n\x08\x64\x65livery\x18\x02 \x03(\x0b\x32\x11.DeliveryResponse\x12\x1c\n\x05\x65rror\x18\x03 \x03(\x0b\x32\r.ErrorMessage\x12\x0b\n\x03\x61\x63k\x18\x04 \x03(\x03\"4\n\nU2ARequest\x12\x19\n\x04\x64\x65st\x18\x01 \x03(\x0b\x32\x0b.UpdateDest\x12\x0b\n\x03\x61\x63k\x18\x02 \x03(\x03\"8\n\x0b\x41\x32UResponse\x12\x1c\n\x05\x65rror\x18\x01 \x03(\x0b\x32\r.ErrorMessage\x12\x0b\n\x03\x61\x63k\x18\x02 \x03(\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_U2ACONNECT = _descriptor.Descriptor(
  name='U2AConnect',
  full_name='U2AConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='U2AConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_U2ACONNECTED = _descriptor.Descriptor(
  name='U2AConnected',
  full_name='U2AConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='U2AConnected.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='U2AConnected.result', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=98,
)


_PICKUPREQUEST = _descriptor.Descriptor(
  name='PickupRequest',
  full_name='PickupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='PickupRequest.seqnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderid', full_name='PickupRequest.orderid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productName', full_name='PickupRequest.productName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='whid', full_name='PickupRequest.whid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wh_x', full_name='PickupRequest.wh_x', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wh_y', full_name='PickupRequest.wh_y', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_x', full_name='PickupRequest.dest_x', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest_y', full_name='PickupRequest.dest_y', index=7,
      number=8, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upsAccount', full_name='PickupRequest.upsAccount', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=264,
)


_PICKUPRESPONSE = _descriptor.Descriptor(
  name='PickupResponse',
  full_name='PickupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='PickupResponse.seqnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracknum', full_name='PickupResponse.tracknum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderid', full_name='PickupResponse.orderid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='PickupResponse.truckid', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=350,
)


_DELIVERYREQUEST = _descriptor.Descriptor(
  name='DeliveryRequest',
  full_name='DeliveryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='DeliveryRequest.seqnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracknum', full_name='DeliveryRequest.tracknum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=403,
)


_DELIVERYRESPONSE = _descriptor.Descriptor(
  name='DeliveryResponse',
  full_name='DeliveryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='DeliveryResponse.seqnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracknum', full_name='DeliveryResponse.tracknum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=457,
)


_UPDATEDEST = _descriptor.Descriptor(
  name='UpdateDest',
  full_name='UpdateDest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UpdateDest.seqnum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tracknum', full_name='UpdateDest.tracknum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_x', full_name='UpdateDest.new_x', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_y', full_name='UpdateDest.new_y', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=535,
)


_ERRORMESSAGE = _descriptor.Descriptor(
  name='ErrorMessage',
  full_name='ErrorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err', full_name='ErrorMessage.err', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='originseqnum', full_name='ErrorMessage.originseqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='ErrorMessage.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=602,
)


_A2UREQUEST = _descriptor.Descriptor(
  name='A2URequest',
  full_name='A2URequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickup', full_name='A2URequest.pickup', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delivery', full_name='A2URequest.delivery', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='A2URequest.ack', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=604,
  serialized_end=697,
)


_U2ARESPONSE = _descriptor.Descriptor(
  name='U2AResponse',
  full_name='U2AResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickup', full_name='U2AResponse.pickup', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delivery', full_name='U2AResponse.delivery', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='U2AResponse.error', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='U2AResponse.ack', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=825,
)


_U2AREQUEST = _descriptor.Descriptor(
  name='U2ARequest',
  full_name='U2ARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest', full_name='U2ARequest.dest', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='U2ARequest.ack', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=827,
  serialized_end=879,
)


_A2URESPONSE = _descriptor.Descriptor(
  name='A2UResponse',
  full_name='A2UResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='A2UResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ack', full_name='A2UResponse.ack', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=881,
  serialized_end=937,
)

_A2UREQUEST.fields_by_name['pickup'].message_type = _PICKUPREQUEST
_A2UREQUEST.fields_by_name['delivery'].message_type = _DELIVERYREQUEST
_U2ARESPONSE.fields_by_name['pickup'].message_type = _PICKUPRESPONSE
_U2ARESPONSE.fields_by_name['delivery'].message_type = _DELIVERYRESPONSE
_U2ARESPONSE.fields_by_name['error'].message_type = _ERRORMESSAGE
_U2AREQUEST.fields_by_name['dest'].message_type = _UPDATEDEST
_A2URESPONSE.fields_by_name['error'].message_type = _ERRORMESSAGE
DESCRIPTOR.message_types_by_name['U2AConnect'] = _U2ACONNECT
DESCRIPTOR.message_types_by_name['U2AConnected'] = _U2ACONNECTED
DESCRIPTOR.message_types_by_name['PickupRequest'] = _PICKUPREQUEST
DESCRIPTOR.message_types_by_name['PickupResponse'] = _PICKUPRESPONSE
DESCRIPTOR.message_types_by_name['DeliveryRequest'] = _DELIVERYREQUEST
DESCRIPTOR.message_types_by_name['DeliveryResponse'] = _DELIVERYRESPONSE
DESCRIPTOR.message_types_by_name['UpdateDest'] = _UPDATEDEST
DESCRIPTOR.message_types_by_name['ErrorMessage'] = _ERRORMESSAGE
DESCRIPTOR.message_types_by_name['A2URequest'] = _A2UREQUEST
DESCRIPTOR.message_types_by_name['U2AResponse'] = _U2ARESPONSE
DESCRIPTOR.message_types_by_name['U2ARequest'] = _U2AREQUEST
DESCRIPTOR.message_types_by_name['A2UResponse'] = _A2URESPONSE

U2AConnect = _reflection.GeneratedProtocolMessageType('U2AConnect', (_message.Message,), dict(
  DESCRIPTOR = _U2ACONNECT,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:U2AConnect)
  ))
_sym_db.RegisterMessage(U2AConnect)

U2AConnected = _reflection.GeneratedProtocolMessageType('U2AConnected', (_message.Message,), dict(
  DESCRIPTOR = _U2ACONNECTED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:U2AConnected)
  ))
_sym_db.RegisterMessage(U2AConnected)

PickupRequest = _reflection.GeneratedProtocolMessageType('PickupRequest', (_message.Message,), dict(
  DESCRIPTOR = _PICKUPREQUEST,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:PickupRequest)
  ))
_sym_db.RegisterMessage(PickupRequest)

PickupResponse = _reflection.GeneratedProtocolMessageType('PickupResponse', (_message.Message,), dict(
  DESCRIPTOR = _PICKUPRESPONSE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:PickupResponse)
  ))
_sym_db.RegisterMessage(PickupResponse)

DeliveryRequest = _reflection.GeneratedProtocolMessageType('DeliveryRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELIVERYREQUEST,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:DeliveryRequest)
  ))
_sym_db.RegisterMessage(DeliveryRequest)

DeliveryResponse = _reflection.GeneratedProtocolMessageType('DeliveryResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELIVERYRESPONSE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:DeliveryResponse)
  ))
_sym_db.RegisterMessage(DeliveryResponse)

UpdateDest = _reflection.GeneratedProtocolMessageType('UpdateDest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEDEST,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UpdateDest)
  ))
_sym_db.RegisterMessage(UpdateDest)

ErrorMessage = _reflection.GeneratedProtocolMessageType('ErrorMessage', (_message.Message,), dict(
  DESCRIPTOR = _ERRORMESSAGE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ErrorMessage)
  ))
_sym_db.RegisterMessage(ErrorMessage)

A2URequest = _reflection.GeneratedProtocolMessageType('A2URequest', (_message.Message,), dict(
  DESCRIPTOR = _A2UREQUEST,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:A2URequest)
  ))
_sym_db.RegisterMessage(A2URequest)

U2AResponse = _reflection.GeneratedProtocolMessageType('U2AResponse', (_message.Message,), dict(
  DESCRIPTOR = _U2ARESPONSE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:U2AResponse)
  ))
_sym_db.RegisterMessage(U2AResponse)

U2ARequest = _reflection.GeneratedProtocolMessageType('U2ARequest', (_message.Message,), dict(
  DESCRIPTOR = _U2AREQUEST,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:U2ARequest)
  ))
_sym_db.RegisterMessage(U2ARequest)

A2UResponse = _reflection.GeneratedProtocolMessageType('A2UResponse', (_message.Message,), dict(
  DESCRIPTOR = _A2URESPONSE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:A2UResponse)
  ))
_sym_db.RegisterMessage(A2UResponse)


# @@protoc_insertion_point(module_scope)
