# Generated by Django 2.1.5 on 2019-02-06 03:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveSmallIntegerField(default=0, verbose_name='owner_id')),
                ('address', models.CharField(default=None, max_length=128, verbose_name='address')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='note')),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 2, 6, 3, 40, 7, 267368, tzinfo=utc), verbose_name='time')),
                ('curr_passenger', models.PositiveSmallIntegerField(default=0, verbose_name='curr_passenger')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='is_confirm')),
                ('driver_id', models.PositiveSmallIntegerField(default=0, verbose_name='driver_id')),
                ('is_complete', models.BooleanField(default=False, verbose_name='is_complete')),
                ('is_shareable', models.BooleanField(default=False, verbose_name='is_shareable')),
            ],
            options={
                'verbose_name': 'Trip Information',
            },
        ),
        migrations.CreateModel(
            name='TripSharerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveSmallIntegerField(default=0, verbose_name='user_id')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharer_list', to='ride_share.Trip')),
            ],
            options={
                'verbose_name': 'TripSharer Information',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_driver', models.BooleanField(default=False, verbose_name='IsDriver')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_driver', models.CharField(blank=True, max_length=128, verbose_name='note_driver')),
                ('type', models.CharField(blank=True, max_length=128, verbose_name='type')),
                ('plate_num', models.CharField(blank=True, max_length=128, verbose_name='plate_num')),
                ('max_passenger', models.PositiveSmallIntegerField(default=0, verbose_name='max_passenger')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='ride_share.Driver')),
            ],
            options={
                'verbose_name': 'Vehicle Information',
            },
        ),
    ]
