# Generated by Django 2.2 on 2019-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0002_auto_20190415_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveSmallIntegerField(default=0, verbose_name='user_id')),
                ('x_pos', models.IntegerField(verbose_name='x_pos')),
                ('y_pos', models.IntegerField(verbose_name='y_pos')),
                ('product_name', models.CharField(max_length=128, verbose_name='product_name')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('status', models.CharField(default='pa', max_length=128, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
