# Generated by Django 2.2 on 2019-04-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0003_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField(default=0, verbose_name='warehouse_id')),
                ('address', models.CharField(max_length=1024, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Warehouse',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_id',
            field=models.IntegerField(default=0, verbose_name='warehouse_id'),
        ),
    ]
