# Generated by Django 2.2 on 2019-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0004_auto_20190419_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_x',
            field=models.IntegerField(default=0, verbose_name='wh_x'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_y',
            field=models.IntegerField(default=0, verbose_name='wh_y'),
        ),
    ]
