# Generated by Django 2.2 on 2019-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0005_auto_20190420_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_num', models.IntegerField(default=0, verbose_name='seq_num')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Ack',
            },
        ),
        migrations.CreateModel(
            name='Messageworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='order_id')),
                ('message', models.CharField(max_length=512, verbose_name='message')),
                ('type', models.CharField(max_length=512, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Messageworld',
            },
        ),
    ]
