# Generated by Django 2.2 on 2019-04-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0006_ack_messageworld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order_id'),
        ),
    ]
