# Generated by Django 2.2 on 2019-04-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0007_auto_20190423_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='none', max_length=128, verbose_name='status'),
        ),
    ]
