# Generated by Django 2.2 on 2019-04-23 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0009_order_ups_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='x_pos',
            field=models.PositiveSmallIntegerField(verbose_name='x_pos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='y_pos',
            field=models.PositiveSmallIntegerField(verbose_name='y_pos'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='warehouse_id'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='wh_x',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wh_x'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='wh_y',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='wh_y'),
        ),
    ]
