# Generated by Django 2.2 on 2019-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0011_auto_20190423_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ack',
            name='ack_num',
            field=models.IntegerField(default=0, verbose_name='ack_num'),
        ),
    ]
